CORREOS = [
    # materiales peligrosos
    {"asunto": "URGENTE: derrame en andén 3",
     "cuerpo": "El camión CAM-102 con placas ABC-123-D presenta fuga de químico inflamable. La báscula marcó 48.5 toneladas. Se requiere apoyo inmediato.",
     "categoria": "materiales_peligrosos", "prioridad": "critica"},
    {"asunto": "Olor raro en la caseta norte",
     "cuerpo": "Un camión de la empresa Quimex trae unos tambos que huelen muy fuerte a solvente, creo que es tóxico, ya llegó a la puerta B.",
     "categoria": "materiales_peligrosos", "prioridad": "alta"},
    {"asunto": "Carga con etiqueta de corrosivo sin documentos",
     "cuerpo": "Llegó el CAM-221 con ácido corrosivo y no trae la hoja de seguridad. Está esperando en el muelle 2.",
     "categoria": "materiales_peligrosos", "prioridad": "alta"},
    {"asunto": "ayuda!! se esta saliendo liquido del tanque",
     "cuerpo": "el camion CAM-77 va escurriendo algo que parece diesel por la puerta C y hay chispas cerca porfa vengan rapido",
     "categoria": "materiales_peligrosos", "prioridad": "critica"},
    {"asunto": "Sobrepeso en camión de gas",
     "cuerpo": "El camión CAM-12 con gas LP excede el peso permitido por 4 toneladas y es carga peligrosa, avisen a seguridad inmediato.",
     "categoria": "materiales_peligrosos", "prioridad": "critica"},

    # sobrepeso
    {"asunto": "Camión con exceso de peso",
     "cuerpo": "El CAM-310 marcó 52 toneladas en la báscula, el límite es 48. Está detenido en la caseta sur.",
     "categoria": "sobrepeso", "prioridad": "media"},
    {"asunto": "sobrecarga en bascula 2",
     "cuerpo": "la bascula marca 61000 kg en el camion CAM-45, esta muy pasado, ya esta bloqueando la salida",
     "categoria": "sobrepeso", "prioridad": "media"},
    {"asunto": "Pasaron la báscula con exceso",
     "cuerpo": "Se detectó que el CAM-88 pasó con exceso de peso y sin pesarse bien, revisar el registro de la báscula.",
     "categoria": "sobrepeso", "prioridad": "media"},

    # acceso no autorizado
    {"asunto": "Intruso en barrera 1",
     "cuerpo": "Una persona sin autorización intentó pasar por la barrera 1 detrás de un camión. Seguridad ya está en el lugar.",
     "categoria": "acceso_no_autorizado", "prioridad": "alta"},
    {"asunto": "Camión sin autorización previa",
     "cuerpo": "El camión de placas XYZ-456-A llegó sin autorizacion y quiere entrar al andén 4, le negamos el acceso.",
     "categoria": "acceso_no_autorizado", "prioridad": "media"},
    {"asunto": "alguien brinco la reja",
     "cuerpo": "vimos a un tipo brincando la reja por el lado de la caseta norte, no es del personal",
     "categoria": "acceso_no_autorizado", "prioridad": "alta"},

    # falla de hardware
    {"asunto": "Cámara LPR no enciende",
     "cuerpo": "La cámara del lector de placas de la puerta B está apagada desde la mañana, no lee ninguna placa.",
     "categoria": "falla_hardware", "prioridad": "media"},
    {"asunto": "Lector RFID dañado",
     "cuerpo": "El lector rfid del carril 2 está dañado, se le cayó el cable. Los camiones no pueden registrarse.",
     "categoria": "falla_hardware", "prioridad": "media"},
    {"asunto": "sensor de la bascula no responde",
     "cuerpo": "el sensor de la bascula esta fallando, marca puros ceros",
     "categoria": "falla_hardware", "prioridad": "media"},
    {"asunto": "Falla eléctrica en la caseta",
     "cuerpo": "Se fue la luz en la caseta y los equipos están apagados, el patio está a oscuras. Es urgente.",
     "categoria": "falla_hardware", "prioridad": "alta"},

    # falla de software
    {"asunto": "Sistema caído",
     "cuerpo": "La aplicación de registro no carga y marca error en pantalla desde hace una hora.",
     "categoria": "falla_software", "prioridad": "alta"},
    {"asunto": "pantalla lenta",
     "cuerpo": "el sistema esta muy lento al buscar placas, tarda como 30 segundos",
     "categoria": "falla_software", "prioridad": "baja"},
    {"asunto": "No me deja iniciar sesión",
     "cuerpo": "Hola, no puedo entrar a mi usuario en el software, me dice contraseña incorrecta.",
     "categoria": "falla_software", "prioridad": "baja"},
    {"asunto": "Error en la báscula virtual",
     "cuerpo": "El programa de la báscula muestra error al guardar el peso del CAM-90.",
     "categoria": "falla_software", "prioridad": "media"},
    {"asunto": "acceso denegado por error",
     "cuerpo": "Al conductor del CAM-150 le salió acceso denegado pero sí tiene su autorización vigente, se está haciendo fila.",
     "categoria": "falla_software", "prioridad": "media"},

    # somnolencia del conductor
    {"asunto": "Conductor dormido",
     "cuerpo": "El conductor del CAM-33 se quedó dormido en la fila y no responde al claxon, parece muy cansado.",
     "categoria": "somnolencia_conductor", "prioridad": "alta"},
    {"asunto": "Alerta de fatiga",
     "cuerpo": "La cámara detectó señales de fatiga y somnolencia en el chofer del CAM-205 mientras entraba al patio.",
     "categoria": "somnolencia_conductor", "prioridad": "alta"},
    {"asunto": "chofer con mucho sueño",
     "cuerpo": "el chofer del cam-19 bosteza y casi choca la barrera, se nota que trae mucho sueño",
     "categoria": "somnolencia_conductor", "prioridad": "alta"},
    {"asunto": "Conductor cansado pide descanso",
     "cuerpo": "El conductor lleva 14 horas manejando y dice que tiene cansancio, pide permiso para descansar en el estacionamiento.",
     "categoria": "somnolencia_conductor", "prioridad": "media"},

    # otro
    {"asunto": "Revisión de rutina de materiales peligrosos",
     "cuerpo": "Les informo que mañana se hará la revisión programada de los camiones con material peligroso. Sin novedades por ahora.",
     "categoria": "otro", "prioridad": "baja"},
    {"asunto": "Duda sobre límite de peso",
     "cuerpo": "Buenas tardes, quisiera saber cuál es el límite de peso para entrar al patio, mi camión cargado pesa 30 toneladas.",
     "categoria": "otro", "prioridad": "baja"},
    {"asunto": "Consulta de horarios",
     "cuerpo": "Buen día, ¿a qué hora abre el patio de maniobras los sábados?",
     "categoria": "otro", "prioridad": "baja"},
    {"asunto": "Solicitud de constancia",
     "cuerpo": "Necesito una constancia de que mi camión ingresó ayer, para mi empresa.",
     "categoria": "otro", "prioridad": "baja"},
    {"asunto": "Felicitaciones al equipo",
     "cuerpo": "Solo quería agradecer al personal de la caseta por la atención de hoy.",
     "categoria": "otro", "prioridad": "baja"},
    {"asunto": "Golpe en el estacionamiento",
     "cuerpo": "Un montacargas golpeó un camión estacionado, hay un herido leve, ya llamamos a la ambulancia.",
     "categoria": "otro", "prioridad": "critica"},
]
